# Manages the 'needs-review' and 'review-complete' labels for PRs
# - 'needs-review' will be added to new PRs *and* when a new commit is pushed
#   if 'review-complete' isn't present
# - 'needs-review' will be removed and 'review-complete' will be added
#   when an approving review is added to the PR
#
# Either label can also be manually added/removed by maintainers.
# E.g., 'needs-review' can be removed if a PR has been reviewed but is not ready to merge,
# so that future commits will trigger the 'needs-review' label again.
name: PR Review Labels

on:
  pull_request_target:
    types: [opened, synchronize]
  pull_request_review:
    types: [submitted]

jobs:
  pr-approved:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_review' &&
      github.event.review.state == 'approved'
    steps:
      - name: Add review-complete label
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: review-complete
          type: add

      - name: Remove needs-review label
        uses: buildsville/add-remove-label@v2.0.1
        if: contains(github.event.pull_request.labels.*.name, 'review-complete')
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: needs-review
          type: remove

  new-commit:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request_target' &&
      !contains(github.event.pull_request.labels.*.name, 'review-complete') &&
      !contains(github.event.pull_request.labels.*.name, 'needs-review')
    steps:
      - name: Add needs-review label
        uses: buildsville/add-remove-label@v2.0.1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: needs-review
          type: add
