# Automatically toggle 'auto-merge' label to track whether automerge is enabled on a PR
# so that we can easily spot them.
name: PR Auto-merge Label

on:
  pull_request_target:
    types: [auto_merge_enabled, auto_merge_disabled]

jobs:
  auto-merge_labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Add auto-merge label
        uses: buildsville/add-remove-label@v2.0.1
        if: github.event.action == 'auto_merge_enabled'
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: auto-merge
          type: add

      - name: Remove auto-merge label
        uses: buildsville/add-remove-label@v2.0.1
        if: github.event.action == 'auto_merge_disabled'
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          labels: auto-merge
          type: remove
