# This workflow automatically labels inactive issues and PRs as 'stale' and ultimately
# close them if they remain inactive.  Inactivity thresholds, and what labels
# qualify (or exempt) an issue or PR from being labeled as 'stale' are defined below.
name: Stale Daemon

on:
  schedule:
    - cron: '45 */4 * * *' # runs at 12:45am UTC, then every 4 hours thereafter

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: 30
          exempt-issue-labels: needs-review, fix
          stale-issue-message: "This issue has been inactive for 30 days and is now marked stale.
            If there is no further activity over the next 7 days, it will be automatically closed."
          stale-issue-label: stale
          days-before-pr-stale: 60
          exempt-pr-labels: needs-review
          stale-pr-message: "This PR has been inactive for 60 days and is now marked stale.
            If there is no further activity over the next 7 days, it will be automatically closed."
          stale-pr-label: stale
          remove-stale-when-updated: true
          days-before-close: 7
          close-issue-message: "This issue was closed because it was marked as stale
            for 7 days with no activity."
          close-issue-reason: not_planned
          close-pr-message: "This PR was closed because it was marked as stale
            for 7 days with no activity."
